### ISSUE TITLE
Problemas importación trabajo año anterior

### ISSUE THREAD

**Issue by ismdepue** [AgoraUS-G1-1617/Creacion-admin-de-votaciones#1]
Problema al importar el trabajo del año pasado del grupo 2 de la asignatura de EGC, debido a problemas con el pom.xml.

**Comment by raftrugon** [comment]
A la hora de intentar desplegar el proyecto del año anterior parece ser que faltan varios .jar y esto imposibilita el poder desplegarlo de forma correcta

**Comment by Armando6464** [comment]
El sistema utiliza en SurveyController la clase AuthorityImpl y un método perteneciente a éste llamado postKey(String.valueOf(survey.getId()), token). Ninguno de estos dos existen actualmente en el sistema.

**Comment by Armando6464** [comment]
El sistema no detecta la versión 2.1.3 del artefacto "Verificacion", el cual es una dependencia especificada en la sección de Verificacion de pom.xml

**Comment by HernanGonzalez42** [comment]
Soy de verificación, seguís teniendo este problema? No sabemos qué subsistemas consumen el jar de Verificación ni qué métodos usan. Por favor, decidnos qué necesitáis de verificación, y si sabéis qué otros subsistemas nos necesitan.

**Comment by ismdepue** [comment]
Asociado el commit a la issue.
