### ISSUE TITLE
Método create() en la API

### ISSUE THREAD

**Issue by Alek7Villa** [AgoraUS-G1-1617/Creacion-admin-de-votaciones#22]
Hola, somos del grupo de creación y administración de censos , necesitaríamos un método en vuestra API que al crear una votación nos devolviese todos sus parámetros y el usuario que ha votado.
Saludos,

**Comment by raftrugon** [comment]
Hola.
Nosotros podemos devolver cada votación que se ha creado, pero no el usuario que ha votado ya que no pertenece a nuestras competencias.

Saludos.
