### ISSUE TITLE
Redirección en cambio de idioma

### ISSUE THREAD

**Issue by Dionakra** [AgoraUS-G1-1617/Creacion-admin-de-votaciones#5]
Buenas.

A la hora de cambiar de idioma la aplicación, bien sea de Inglés a Español o viceversa, ésta redirige a la página principal. Por ejemplo, si accedemos al apartado "sobre nosotros" (https://beta.cavotacion.agoraus1.egc.duckdns.org/welcome/aboutus.do) y cambiamos el idioma, nos redirige a la página principal, teniendo que rehacer el camino que se haya hecho.

En este caso no es crítico, pero en cuanto la aplicación avance pudiera ser un problema.

Saludos.

**Comment by JaviPalla** [comment]
Solucionado mediante un poco de código Javascript
