### ISSUE TITLE
Acceso restringido a la API de votaciones

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Creacion-admin-de-votaciones#6]
Saludos compañeros de AgoraUS,
Soy miembro del equipo de Frontend y estoy teniendo un problemilla para mostrar los datos en nuestro subsistema. Para arreglarlo, tenemos que obtener las encuestas directamente de vuestro módulo.
He probado a conectarme a la página desplegada, https://beta.cavotacion.agoraus1.egc.duckdns.org/survey/finishedSurveys
pero se redirige a la página del login, cuando estas deberían ser públicas. En general, cualquier url que intente usar me redirige, salvo la de inicio.
¿Alguna idea de por qué ocurre esto?
Saludos y gracias

**Comment by anddonram** [comment]
Me gustaría también que añadierais el campo codigo postal al tipo Survey. Nos hace falta para mostrar un mapa con el número de encuestas repartidas por España

**Comment by raftrugon** [comment]
Muy bien, tomamos nota y cuando este arreglado avisamos.

**Comment by Armando6464** [comment]
Solucionado error de restricción de acceso, ahora debería funcionar correctamente. Además, implementado el atributo postalCode en la clase Survey.
