### ISSUE TITLE
Mejoras en la API

### ISSUE THREAD

**Issue by raftrugon** [AgoraUS-G1-1617/Creacion-admin-de-votaciones#7]
Implementación de varios métodos en la API del sistema.

**Comment by raftrugon** [comment]
Se han añadido las referencias a los commits.

**Comment by ismdepue** [comment]
Se han añadido referencia a otros commits relacionado con este issue, para agruparlas de forma que sea más fácil trabajar teniendo todos los commits relacionado con la API en la misma issue.
