### ISSUE TITLE
Funcionalidad de la Query allFinishedSurveys incorrecta

### ISSUE THREAD

**Issue by Armando6464** [AgoraUS-G1-1617/Creacion-admin-de-votaciones#9]
Buenas. Revisando el código del repositorio de Survey, he podido comprobar que la query "allFinishedSurveys" debe devolver una lista de Surveys cuya fecha de finalización sea igual a la fecha actual del sistema. Sin embargo, el código JPQL busca aquellas Surveys cuya fecha de finalización sea igual a una fecha pasada como parámetro. ¿Coincide realmente la query escrita con el enunciado de ésta?

Además, el nombre del método "allFinishedSurveys" hace entender al usuario que dicha query recogerá todas las Surveys cuya fecha de finalización es más antigua que la fecha actual. Sin embargo, la nuestra recoge las Surveys cuya fecha de finalización sea exactamente la misma que la actual. ¿No tendría más funcionalidad implementándose de la primera forma?

Saludos.

**Comment by raftrugon** [comment]
Se ha solucionado el fallo, tan solo hubo que eliminar el parámetro que recibía el método tanto en el repositorio como en el servicio.
